import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import cf from '../cf';

interface MethodInfo {
    phpdoc: string;
    signature: string;
}

interface ClassInfo {
    name: string;
    phpdoc: string;
    methods: MethodInfo[];
    useStatements: string[];
}

function extractClassInfo(filePath: string): ClassInfo | null {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');

    const classMatch = content.match(/^(?:abstract\s+|final\s+)?class\s+(\w+)/m);
    if (!classMatch) { return null; }

    const className = classMatch[1];

    const useStatements: string[] = [];
    const useRegex = /^use\s+(.+);/;
    for (const line of lines) {
        const m = line.match(useRegex);
        if (m) {
            useStatements.push(m[0]);
        }
    }

    let classPhpdoc = '';
    const classLineIndex = lines.findIndex(l => l.match(/^(?:abstract\s+|final\s+)?class\s+/));
    if (classLineIndex > 0) {
        let docEnd = classLineIndex - 1;
        while (docEnd >= 0 && lines[docEnd].trim() === '') { docEnd--; }
        if (docEnd >= 0 && lines[docEnd].trim().endsWith('*/')) {
            let docStart = docEnd;
            while (docStart > 0 && !lines[docStart].trim().startsWith('/**')) { docStart--; }
            if (lines[docStart].trim().startsWith('/**')) {
                classPhpdoc = lines.slice(docStart, docEnd + 1).join('\n');
            }
        }
    }

    const methods: MethodInfo[] = [];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const methodMatch = line.match(/^\s*public\s+static\s+function\s+(\w+)\s*\(/);
        if (!methodMatch) { continue; }

        let signature = line.trim();
        if (!signature.includes(')')) {
            let j = i + 1;
            while (j < lines.length && !lines[j].includes(')')) {
                signature += '\n' + lines[j].trim();
                j++;
            }
            if (j < lines.length) {
                signature += '\n' + lines[j].trim();
            }
        }

        signature = signature.replace(/\)\s*(\{|:).*$/, ')');
        const braceIdx = signature.indexOf('{');
        if (braceIdx > 0) {
            signature = signature.substring(0, braceIdx).trim();
        }
        if (!signature.endsWith(')')) {
            const parenIdx = signature.lastIndexOf(')');
            if (parenIdx > 0) {
                signature = signature.substring(0, parenIdx + 1);
            }
        }

        let phpdoc = '';
        let docEnd = i - 1;
        while (docEnd >= 0 && lines[docEnd].trim() === '') { docEnd--; }
        if (docEnd >= 0 && lines[docEnd].trim().endsWith('*/')) {
            let docStart = docEnd;
            while (docStart > 0 && !lines[docStart].trim().startsWith('/**')) { docStart--; }
            if (lines[docStart].trim().startsWith('/**')) {
                phpdoc = lines.slice(docStart, docEnd + 1).map(l => '    ' + l.trim()).join('\n');
            }
        }

        methods.push({ phpdoc, signature: '    ' + signature + ' {}' });
    }

    return { name: className, phpdoc: classPhpdoc, methods, useStatements };
}

function generateStubContent(classes: ClassInfo[]): string {
    const header = `<?php
/**
 * CF IDE Helper — auto-generated stub file for Cresenity Framework.
 *
 * Provides PHPDoc stubs so that IDEs (Intelephense, PhpStorm, etc.)
 * can offer autocomplete, hover, and go-to-definition for CF helper classes.
 *
 * This file should NOT be included in production code.
 * Add it to your .gitignore if desired.
 *
 * @generated by CF PHP Extension
 */

`;

    let output = header;

    for (const cls of classes) {
        if (cls.phpdoc) {
            output += cls.phpdoc + '\n';
        }
        output += `class ${cls.name} {\n`;
        for (const method of cls.methods) {
            if (method.phpdoc) {
                output += method.phpdoc + '\n';
            }
            output += method.signature + '\n\n';
        }
        output += '}\n\n';
    }

    return output;
}

export default async function generateIdeHelperCommand() {
    const docRoot = cf.getDocRoot();
    if (!docRoot) {
        vscode.window.showWarningMessage('CF project not detected.');
        return;
    }

    const helpersDir = path.join(docRoot, 'system', 'helpers');
    const coreDir = path.join(docRoot, 'system', 'core');
    const librariesDir = path.join(docRoot, 'system', 'libraries');

    const libraryFiles = [
        'CApp.php', 'CModel.php', 'CHTTP.php', 'CCache.php', 'CAuth.php',
        'CRouting.php', 'CStorage.php', 'CConsole.php', 'CManager.php',
        'CValidation.php', 'CCollection.php', 'CJavascript.php',
        'CDomain.php', 'CEvent.php', 'CElement.php',
    ];

    const scanDirs: { dir: string; files?: string[] }[] = [];

    if (fs.existsSync(helpersDir)) {
        scanDirs.push({ dir: helpersDir });
    }
    if (fs.existsSync(coreDir)) {
        scanDirs.push({ dir: coreDir, files: ['CF.php'] });
    }
    if (fs.existsSync(librariesDir)) {
        const existingLibFiles = libraryFiles.filter(f => fs.existsSync(path.join(librariesDir, f)));
        if (existingLibFiles.length > 0) {
            scanDirs.push({ dir: librariesDir, files: existingLibFiles });
        }
    }

    if (scanDirs.length === 0) {
        vscode.window.showWarningMessage('No CF system directory found.');
        return;
    }

    const classes: ClassInfo[] = [];

    await vscode.window.withProgress({
        location: vscode.ProgressLocation.Notification,
        title: 'Generating CF IDE Helper...',
        cancellable: false,
    }, async (progress) => {
        for (const entry of scanDirs) {
            let files: string[];
            if (entry.files) {
                files = entry.files;
            } else {
                files = fs.readdirSync(entry.dir).filter(f => f.endsWith('.php')).sort();
            }

            for (const file of files) {
                const filePath = path.join(entry.dir, file);
                if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) { continue; }

                progress.report({ message: file });

                const info = extractClassInfo(filePath);
                if (info && info.methods.length > 0) {
                    classes.push(info);
                }
            }
        }
    });

    if (classes.length === 0) {
        vscode.window.showWarningMessage('No helper classes found to generate stubs for.');
        return;
    }

    const stubContent = generateStubContent(classes);
    const outputPath = path.join(docRoot, '_ide_helper.php');
    fs.writeFileSync(outputPath, stubContent, 'utf-8');

    const totalMethods = classes.reduce((sum, cls) => sum + cls.methods.length, 0);

    const action = await vscode.window.showInformationMessage(
        `IDE Helper generated: ${classes.length} classes, ${totalMethods} methods → _ide_helper.php`,
        'Open File'
    );

    if (action === 'Open File') {
        const doc = await vscode.workspace.openTextDocument(outputPath);
        await vscode.window.showTextDocument(doc);
    }
}
